=== marcinCzapiewski/XmlLanguages/lab4/zad2.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT wyniki (przedmiot*) >
<!ELEMENT przedmiot (nazwa, egzaminator, rodzaj, ocena) >
<!ELEMENT egzaminator (tytul, imie, nazwisko) >
<!ELEMENT nazwa (#PCDATA) >
<!ELEMENT rodzaj (#PCDATA) >
<!ELEMENT ocena (#PCDATA) >
<!ELEMENT tytul (#PCDATA) >
<!ELEMENT imie (#PCDATA) >
<!ELEMENT nazwisko (#PCDATA) >

<!ENTITY algo "Algorytmy">
<!ENTITY dr "doktor">
<!ENTITY w "wykład">
<!ENTITY db "dobry">
<!ENTITY prof "profesor">
<!ENTITY hab "habilitowany">
<!ENTITY cw "ćwiczenia audytoryjne">
<!ENTITY dstp "dostateczny plus">
<!ENTITY mat "Matematyka">
<!ENTITY mgr "magister">
<!ENTITY prog "Programowanie">
<!ENTITY dst "dostateczny">
<!ENTITY lab "ćwiczenia laboratoryjne">
<!ENTITY dbp "dobry plus">
<!ENTITY sk "Sieci komputerowe">
<!ENTITY inz "inżynier">
<!ENTITY so "Systemy operacyjne">
<!ENTITY x "XML">
<!ENTITY bdb "bardzo dobry">

=== marcinCzapiewski/XmlLanguages/lab4/zad2.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE wyniki SYSTEM "zad2.dtd">

<wyniki>
	<przedmiot>
		<nazwa>&algo;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Pankracy</imie>
			<nazwisko>Bajeczny</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&db;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&algo;</nazwa>
		<egzaminator>
			<tytul>&prof;, &dr; &hab;</tytul>
			<imie>Bianor</imie>
			<nazwisko>Łysy</nazwisko>
		</egzaminator>
		<rodzaj>&cw;</rodzaj>
		<ocena>&dstp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&mat;</nazwa>
		<egzaminator>
			<tytul>&dr; &hab;</tytul>
			<imie>Marcel</imie>
			<nazwisko>Chabacki</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&dstp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&mat;</nazwa>
		<egzaminator>
			<tytul>&mgr;</tytul>
			<imie>Klet</imie>
			<nazwisko>Zabacki</nazwisko>
		</egzaminator>
		<rodzaj>&cw;</rodzaj>
		<ocena>&dstp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&prog;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Amon</imie>
			<nazwisko>Fabacki</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&dst;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&prog;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Fidol</imie>
			<nazwisko>Jadacki</nazwisko>
		</egzaminator>
		<rodzaj>&cw;</rodzaj>
		<ocena>&db;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&prog;</nazwa>
		<egzaminator>
			<tytul>&mgr;</tytul>
			<imie>Klet</imie>
			<nazwisko>Zabacki</nazwisko>
		</egzaminator>
		<rodzaj>&lab;</rodzaj>
		<ocena>&dbp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&sk;</nazwa>
		<egzaminator>
			<tytul>&dr; &inz;</tytul>
			<imie>Kanizjusz</imie>
			<nazwisko>Miłosierny</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&db;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&sk;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Pankracy</imie>
			<nazwisko>Bajeczny</nazwisko>
		</egzaminator>
		<rodzaj>&cw;</rodzaj>
		<ocena>&dst;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&so;</nazwa>
		<egzaminator>
			<tytul>&dr; &inz;</tytul>
			<imie>Ksawery</imie>
			<nazwisko>Melon</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&dbp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&so;</nazwa>
		<egzaminator>
			<tytul>&dr; &inz;</tytul>
			<imie>Ksawery</imie>
			<nazwisko>Melon</nazwisko>
		</egzaminator>
		<rodzaj>&lab;</rodzaj>
		<ocena>&dbp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&x;</nazwa>
		<egzaminator>
			<tytul>&prof;, &dr; &hab;</tytul>
			<imie>Ramzes</imie>
			<nazwisko>Koniczyna</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&bdb;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&x;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Scholastyka</imie>
			<nazwisko>Bławatek</nazwisko>
		</egzaminator>
		<rodzaj>&lab;</rodzaj>
		<ocena>&bdb;</ocena>
	</przedmiot>
</wyniki>
